FROM centos:latest
MAINTAINER "The CentOS Project" <admin@jiobxn.com>

RUN \cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN yum clean all; yum -y install epel-release; yum -y update; yum -y install nginx net-tools bash-completion vim wget iptables cronie; yum clean all

VOLUME /usr/share/nginx/html /key

COPY nginx-rpm.sh /nginx-rpm.sh
RUN chmod +x /nginx-rpm.sh

ENTRYPOINT ["/nginx-rpm.sh"]

EXPOSE 80 443

CMD ["nginx"]

# docker build -t nginx-rpm .
# docker run -d --restart always -p 80:80 -p 443:443 -v /docker/www:/www -v /docker/nginx:/key -e DOMAIN_PROXY="fqhub.com%backend_https=y" -e PROXY_SERVER="jiobxn.com,www.jiobxn.com|jiobxn.wordpress.com%backend_https=y,alias=/down|/www" --hostname nginx --name test-nginx nginx
# docker run -it --rm nginx-rpm --help
