FROM centos:latest
MAINTAINER "The CentOS Project" <admin@jiobxn.com>

RUN \cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN nginx_url="http://nginx.org/packages/centos/$(awk '{print $4}' /etc/redhat-release |awk -F. '{print $1}')/noarch/RPMS/" \
    && rpm -ivh $nginx_url$(curl -s $nginx_url |grep release |awk -F\" '{print $2}')
RUN yum clean all; yum -y update; yum -y install nginx net-tools bash-completion vim wget iptables cronie; yum clean all

VOLUME /usr/share/nginx/html /key

COPY nginx-rpm.sh /nginx-rpm.sh
RUN chmod +x /nginx-rpm.sh

ENTRYPOINT ["/nginx-rpm.sh"]

EXPOSE 80 443

CMD ["nginx"]

# docker build -t nginx-rpm .
# docker run -d --restart always -p 10080:80 -p 10443:443 -v /docker/www:/usr/share/nginx/html -e PHP_SERVER=redhat.xyz:9000 --hostname nginx --name nginx nginx-rpm
# docker run -d --restart always -p 10080:80 -p 10443:443 -v /docker/webapps:/usr/share/nginx/html -e JAVA_SERVER=redhat.xyz:18080 --hostname nginx --name nginx nginx-rpm
# docker run -it --rm nginx-rpm --help
